// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: lyexamination.proto

package lyexamination

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WechatLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WechatLoginReq) Reset() {
	*x = WechatLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lyexamination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatLoginReq) ProtoMessage() {}

func (x *WechatLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_lyexamination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatLoginReq.ProtoReflect.Descriptor instead.
func (*WechatLoginReq) Descriptor() ([]byte, []int) {
	return file_lyexamination_proto_rawDescGZIP(), []int{0}
}

type WechatLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrCode string `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
}

func (x *WechatLoginRes) Reset() {
	*x = WechatLoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lyexamination_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatLoginRes) ProtoMessage() {}

func (x *WechatLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_lyexamination_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatLoginRes.ProtoReflect.Descriptor instead.
func (*WechatLoginRes) Descriptor() ([]byte, []int) {
	return file_lyexamination_proto_rawDescGZIP(), []int{1}
}

func (x *WechatLoginRes) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type WechatMonitorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WechatMonitorReq) Reset() {
	*x = WechatMonitorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lyexamination_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatMonitorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatMonitorReq) ProtoMessage() {}

func (x *WechatMonitorReq) ProtoReflect() protoreflect.Message {
	mi := &file_lyexamination_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatMonitorReq.ProtoReflect.Descriptor instead.
func (*WechatMonitorReq) Descriptor() ([]byte, []int) {
	return file_lyexamination_proto_rawDescGZIP(), []int{2}
}

type WechatMonitorRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WechatMonitorRes) Reset() {
	*x = WechatMonitorRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lyexamination_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatMonitorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatMonitorRes) ProtoMessage() {}

func (x *WechatMonitorRes) ProtoReflect() protoreflect.Message {
	mi := &file_lyexamination_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatMonitorRes.ProtoReflect.Descriptor instead.
func (*WechatMonitorRes) Descriptor() ([]byte, []int) {
	return file_lyexamination_proto_rawDescGZIP(), []int{3}
}

func (x *WechatMonitorRes) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_lyexamination_proto protoreflect.FileDescriptor

var file_lyexamination_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x79, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x29, 0x0a, 0x0e, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x22, 0x2a, 0x0a, 0x10, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74,
	0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x8b, 0x01, 0x0a, 0x0d, 0x4c, 0x59, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x57,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x57, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x57, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x14, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x11, 0x2e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x57, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x2e, 0x71, 0x69, 0x61, 0x6e, 0x6a, 0x75, 0x6e, 0x61,
	0x6b, 0x61, 0x73, 0x75, 0x6d, 0x69, 0x2e, 0x72, 0x65, 0x6e, 0x2f, 0x6c, 0x79, 0x65, 0x78, 0x61,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x79, 0x65,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_lyexamination_proto_rawDescOnce sync.Once
	file_lyexamination_proto_rawDescData = file_lyexamination_proto_rawDesc
)

func file_lyexamination_proto_rawDescGZIP() []byte {
	file_lyexamination_proto_rawDescOnce.Do(func() {
		file_lyexamination_proto_rawDescData = protoimpl.X.CompressGZIP(file_lyexamination_proto_rawDescData)
	})
	return file_lyexamination_proto_rawDescData
}

var file_lyexamination_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lyexamination_proto_goTypes = []interface{}{
	(*WechatLoginReq)(nil),   // 0: WechatLoginReq
	(*WechatLoginRes)(nil),   // 1: WechatLoginRes
	(*WechatMonitorReq)(nil), // 2: WechatMonitorReq
	(*WechatMonitorRes)(nil), // 3: WechatMonitorRes
}
var file_lyexamination_proto_depIdxs = []int32{
	0, // 0: LYExamination.AccountWechatLogin:input_type -> WechatLoginReq
	2, // 1: LYExamination.AccountWechatMonitor:input_type -> WechatMonitorReq
	1, // 2: LYExamination.AccountWechatLogin:output_type -> WechatLoginRes
	3, // 3: LYExamination.AccountWechatMonitor:output_type -> WechatMonitorRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lyexamination_proto_init() }
func file_lyexamination_proto_init() {
	if File_lyexamination_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lyexamination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lyexamination_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatLoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lyexamination_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatMonitorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lyexamination_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatMonitorRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lyexamination_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lyexamination_proto_goTypes,
		DependencyIndexes: file_lyexamination_proto_depIdxs,
		MessageInfos:      file_lyexamination_proto_msgTypes,
	}.Build()
	File_lyexamination_proto = out.File
	file_lyexamination_proto_rawDesc = nil
	file_lyexamination_proto_goTypes = nil
	file_lyexamination_proto_depIdxs = nil
}
